Numpy : 
    workig with array
    contain simple math functions
    

In [36]:
import numpy as np

arr= np.array([1,2,3,4])

print(arr)
print(arr.size)
print(arr.shape)
print(type(arr))

[1 2 3 4]
4
(4,)
<class 'numpy.ndarray'>


In [42]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)

print(arr[1])#element accessing
print(arr[1:4])#slicing
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1, 2]) #advance indexing


[1 2 3 4 5]
2
[2 3 4]
6


In [46]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
#simple math function
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
#randam module
print(np.random.rand(2))
print(np.random.randint(3))

[1 2 3 4 5]
15
3.0
1.4142135623730951
[0.68195824 0.22945081]
2


Pandas : 
    working with datasets
    easy for multidimentional labled array
    pandas have series
    dataframe is writen as dict

In [53]:
import pandas as pd

y= pd.Series([1,2,3,4,5])#series
print(y)

#create dataframe
data ={
    'A':[1,2,3],
    'B':[4,5,6]
}
df=pd.DataFrame(data)
print(df['A'])

df['C'] = df['A'] + df['B']
print(df['C'])

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
Name: A, dtype: int64
0    5
1    7
2    9
Name: C, dtype: int64
